//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelry.DTO.Model.DTO

{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerDTO()
        {
            this.AddressesDTO = new HashSet<AddressDTO>();
            this.OrdersDTO = new HashSet<OrderDTO>();
            this.CommentsDTO = new HashSet<CommentDTO>();
            this.FavoriteProductsDTO = new HashSet<FavoriteProductDTO>();
        }
    
        public int CustomerID { get; set; }
        [Required(ErrorMessage = "Kullanýcý adý boþ geçilemez.")]
        [RegularExpression(@"^([a-zA-Z])[a-zA-Z_-]*[\w_-]*[\S]$|^([a-zA-Z])[0-9_-]*[\S]$|^[a-zA-Z]*[\S]$", ErrorMessage = "Kullanýcý adýnýzda harf, sayý ya da '_' haricinde karakter bulunumaz.")]
        [Display(Name = "Adýnýz")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Soyisim boþ geçilemez.")]
        [Display(Name = "Soyadýnýz")]
        public string LastName { get; set; }
        [EmailAddress(ErrorMessage = "---@---.com formatýnda bir giriþ yapýnýz."), Required(ErrorMessage = "E-Posta boþ geçilemez")]
        [Display(Name = "E-mail Adresiniz")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Þifre boþ geçilemez")]
        [Display(Name = "Þifreniz")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Yeni Þifrenizin Tekrarý Zorunludur")]
        [Compare(otherProperty: "Password", ErrorMessage = "Þifreler uyuþmuyor.")]
        [Display(Name = "Þifreniz Tekrar")]
        public string ComparePassword { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Role { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressDTO> AddressesDTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDTO> OrdersDTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentDTO> CommentsDTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteProductDTO> FavoriteProductsDTO { get; set; }
    }
}
