//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelry.DTO.Model.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteProductDTO
    {
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CustomerDTO CustomerDTO { get; set; }
        public virtual ProductDTO ProductDTO { get; set; }
    }
}
