//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelry.DTO.Model.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDTO
    {
        
        public OrderDTO()
        {
            this.OrderDetailsDTO = new HashSet<OrderDetailDTO>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int AddressID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string ShippAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipCountry { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual CustomerDTO CustomerDTO { get; set; }
        public virtual AddressDTO AddressDTO { get; set; }
        public virtual ICollection<OrderDetailDTO> OrderDetailsDTO { get; set; }
        
    }
}
