//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelry.DTO.Model.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailDTO
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }

        public Nullable<decimal> TotalPrice
        {
            get
            {
                return Quantity.Value*UnitPrice.Value;
            }
            
        }

        public Nullable<short> Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }

        public string ProductName { get; set; }
        public string ProductPhoto { get; set; }
        //public virtual OrderDTO Order { get; set; }
        //public virtual ProductDTO Product { get; set; }
    }
}
